-- This script was generated by the Schema Diff utility in pgAdmin 4
-- For the circular dependencies, the order in which Schema Diff writes the objects is not very sophisticated
-- and may require manual changes to the script to ensure changes are applied in the correct order.
-- Please report an issue for any failure with the reproduction steps.

CREATE OR REPLACE FUNCTION public.test(
	)
    RETURNS integer
    LANGUAGE 'plpgsql'
    COST 100
    VOLATILE SECURITY DEFINER PARALLEL UNSAFE
AS $BODY$
  declare
    bind_permissions int;
  begin
    select
      count(*)
    from public.todo_list   
    
    into bind_permissions;

    return bind_permissions;
  end;
$BODY$;

ALTER FUNCTION public.test()
    OWNER TO postgres;

GRANT EXECUTE ON FUNCTION public.test() TO PUBLIC;

GRANT EXECUTE ON FUNCTION public.test() TO anon;

GRANT EXECUTE ON FUNCTION public.test() TO authenticated;

GRANT EXECUTE ON FUNCTION public.test() TO postgres;

GRANT EXECUTE ON FUNCTION public.test() TO service_role;
